# Digital Signal Processing
## Convolution and Correlation

### MsCV - ViBOT - MAIA

In [50]:
%matplotlib inline
%pprint off

# To make some nice plot
import matplotlib.pyplot as plt
# To play with arrays
import numpy as np
from skimage import io
from skimage import img_as_float
from matplotlib import cm
import math

def dirac(n=0, N=20):
    if n > N-1: raise ValueError('n is out of range')
    s = np.zeros((N, ))
    s[n] = 1
    return s
def H_FUNC(n=0, N=5):
    if n > N-1: raise ValueError('n is out of range')
    s = np.zeros((N, ))
    for i in range(0, s.size):
        s[i] = 1
    return s

Pretty printing has been turned ON


## Exercise 1- 1D Convolution

**1.1** Defining a signal $x$ and an impulse response $h$ as parameters, write a program `conv_fn` to compute the convolution product $y=h*x$. Do not use the python or matlab function and just consider zero padding to solve the border problem.

**1.2** Test your function, while using the following signal ($x[n] = \{\underline{1},2,3,4\}$) and following filters, ($\delta[k]$, $H[k]$, $e^{k}$, and $h = \{-1, 1\}$), respectively.

**1.3** Consider the previous input signal, write it's extended version while considering `symmetry`, `periodic` and `constant values` padding and $h = H[k-5]$



for symetric padding [-3.  1.  1.  1.  0. -1. -1. -1.  0.  1.  1.  1.]
for periodic padding [ 3. -1. -1. -1.  3. -1. -1. -1.  3. -1. -1. -1.]
for constant padding [ 3.  0.  0.  0.  0. -1. -1. -1.  0.  0.  0.  0.]

In [60]:
def conv_fn(x0,h) :
    if(x0.size == 0 | h.size == 0):
        raise Exception('Input cannot be empty')
        
    x = np.zeros(x0.size + 2*h.size)
    for i in range(0, x0.size):
        x[i + h.size] = x0[i]
  
    h_flip = h[::-1]
   # print h_flip
   # print x
    con = np.zeros(x.size)
    for i in range(0, x.size):
        for j in range(0, h.size):
            con[i] += x[i-j] * h[j]
            
    return con
# 

In [61]:
x = np.array([1, 2, 3, 4])
h = np.array([-1,1])

print '================ 1 =================='
res = np.convolve(x,h)
print conv_fn(x,h)
print 'python built in res: '
print res

print '================ 2 =================='
x2 = np.array([1, 2, 3, 4])
h2 = dirac(0,5)

res2 = np.convolve(x2,h2)
print conv_fn(x2,h2)
print 'python built in res: '
print res2

print '================ 3 =================='
x3 = np.array([1, 2, 3, 4])
h3 = np.zeros(6)
for i in range(0,h3.size):
    h3[i] = math.exp(i)
    
res3 = np.convolve(x3,h3)
print conv_fn(x3,h3)
print 'python built in res: '
print res3

print '================ 4 =================='
x4 = np.array([1, 2, 3, 4])
h4 = H_FUNC(0,5)

res4 = np.convolve(x4,h4)
print conv_fn(x4,h4)
print 'python built in res: '
print res4

print '================ 5 =================='
x5 = np.array([4,3,2,1,1, 2, 3, 4,4,3,2,1])
h5 = H_FUNC(0,5)

res5 = np.convolve(x5,h5)
print conv_fn(x5,h5)
print 'python built in res: '
print res5

================ 1 ==================
[ 0.  0. -1. -1. -1. -1.  4.  0.]
python built in res: 
[-1 -1 -1 -1  4]
================ 2 ==================
[ 0.  0.  0.  0.  0.  1.  2.  3.  4.  0.  0.  0.  0.  0.]
python built in res: 
[ 1.  2.  3.  4.  0.  0.  0.  0.]
================ 3 ==================
[   0.            0.            0.            0.            0.            0.
    1.            4.71828183   15.82561976   47.01849461  127.80951949
  347.42229433  540.962916    663.63207744  593.65263641    0.        ]
python built in res: 
[   1.            4.71828183   15.82561976   47.01849461  127.80951949
  347.42229433  540.962916    663.63207744  593.65263641]
================ 4 ==================
[  0.   0.   0.   0.   0.   1.   3.   6.  10.  10.   9.   7.   4.   0.]
python built in res: 
[  1.   3.   6.  10.  10.   9.   7.   4.]
================ 5 ==================
[  0.   0.   0.   0.   0.   4.   7.   9.  10.  11.   9.   9.  11.  14.  16.
  16.  14.  10.   6.   3.   1.   0.]
pyt

## Exercise 2- 2D Convolution

**2.1** Define a 2D convolution function (Only consider zero-padding the image)

**2.2** Using your function, smooth the `lena` image with the following Gaussian kernel:
$$ K = \frac{1.}{256}\begin{bmatrix} 1 & 4 & 6 & 4 & 1 \\ 4 & 16 & 24 & 16 & 4 \\ 6 & 24 & 36 & 24 & 6 \\ 4 & 16 & 24 & 16 & 4 \\ 1 & 4 & 6 & 4 & 1 \end{bmatrix}$$

**2.3** Apply sobel filtering using convolution


In [10]:
def conv_fun_2D:
    if(x0.size == 0 | h.size == 0):
        raise Exception('Input cannot be empty')

## Exercise 3 - Character recognition using cross-correlation

**3.1** load `a.png` and `text.png` images and binarized them using [`threshold_otsu`](http://scikit-image.org/docs/dev/api/skimage.filters.html?highlight=filters#skimage.filters.threshold_otsu)

**3.2** Use [`signal.correlate2d`](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.signal.correlate2d.html#scipy.signal.correlate2d) from `scipy` to correlate your binarized images.
**Note, signal correspond to the bright pixels within and image (invert your masks)**

**3.3** Find the first 10 characters recognized as `a`.